version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always
    networks:
      - back
      - default
  db1:
    image: postgres:10.1
    ports:
      - 15432:5432
    env_file: .env_postgres
    environment:
      - DATABASE_USER=postgres
    networks:
      - back
  db2:
    image: postgres:10.1
    ports:
      - 25432:5432
    env_file: .env_postgres
    environment:
      - DATABASE_USER=postgres
    networks:
      - back
  web:
    image: euclid3620/rails_sandbox:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    env_file: 
      - .env
      - .env_postgres
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
      - DATABASE_PRIMARY_HOST=db1
      - DATABASE_SECONDARY_HOST=db2
      - DATABASE_USER=postgres
    tty: true
    depends_on:
      - db1
      - db2
    networks:
      - back
      - default

networks:
  back: