version: '3'
services:
#  db:
#    image: postgres
  web:
    image: euclid3620/rails_sandbox:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    tty: true
#    depends_on:
#      - db