inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/spring
    - node_modules/**/*
  TargetRubyVersion: 2.6

# Offense count: 326
Metrics/LineLength:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'bin/*'
    - 'config/**/*'
  Max: 100